<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>cfg</string>
	</array>
	<key>name</key>
	<string>MOHAA Config</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>comment</key>
			<string>Comment lines</string>
			<key>match</key>
			<string>\s*\/\/\s*.*</string>
			<key>name</key>
			<string>comment.line.cfg</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(["])</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\1)|(\n)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>invalid.illegal.newline</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.double.cfg</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\\s*\n</string>
					<key>name</key>
					<string>constant.character.escape.newline</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\\[nrt"\\]</string>
					<key>name</key>
					<string>constant.character.escape</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>comment</key>
			<string>Semicolon</string>
			<key>match</key>
			<string>\;</string>
			<key>name</key>
			<string>punctuation.terminator.statement</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Functions</string>
			<key>match</key>
			<string>\b(add|alias|altbind|append|bind|bindlist|clear|cmd|ctrlbind|cvar_restart|echo|exec|map|quit|rcon|reset|restart|say|sayone|sayprivate|sayteam|scale|set|seta|sets|setu|subtract|toggle|unaltbind|unbind|unbindall|unctrlbind|vstr|wait|wisper|writeconfig)\b</string>
			<key>name</key>
			<string>support.function</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Numbers</string>
			<key>match</key>
			<string>\b\d+\.?(?:\d+)?\b</string>
			<key>name</key>
			<string>constant.numeric.cfg</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.cfg</string>
	<key>uuid</key>
	<string>7368b9d3-8779-4ed2-bc48-cd08ff644e5a</string>
</dict>
</plist>
