<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>log</string>
	</array>
	<key>name</key>
	<string>MOHAA Log</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#string</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#numeric</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#info</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#errors</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#script_error</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#critical</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#client</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#other</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>client</key>
		<dict>
			<key>match</key>
			<string>^(clientCommand:|clientDownload:)|^.+has entered the battle$</string>
			<key>name</key>
			<string>entity.name</string>
		</dict>
		<key>critical</key>
		<dict>
			<key>match</key>
			<string>(-{5} Server Shutdown -{5}|={4} ShutdownGame ={4}|LoadLibrary.+failed|Info string length exceeded|pending server commands|NET_CompareAdr:)</string>
			<key>name</key>
			<string>invalid</string>
		</dict>
		<key>errors</key>
		<dict>
			<key>match</key>
			<string>^((\^~\^~\^ (Script Error:)*)|ERROR:|WARNING[:-]|Warning:|Hitch warning:|Reborn WARNING:|ERROR PlaySound:|DUPLICATE ALIASES:|couldn\'t exec|Server Shutdown|TIKI_InitTiki:)</string>
			<key>name</key>
			<string>keyword.control</string>
		</dict>
		<key>info</key>
		<dict>
			<key>match</key>
			<string>(Cvar_Set2:|Reborn INFO:|--&gt;|(-|=){4,30})</string>
			<key>name</key>
			<string>variable.parameter.function</string>
		</dict>
		<key>numeric</key>
		<dict>
			<key>match</key>
			<string>\b((0(x|X)[0-9a-fA-F]+)|([0-9]+(\.[0-9]+)?))\b</string>
			<key>name</key>
			<string>constant.numeric.mohaa</string>
		</dict>
		<key>other</key>
		<dict>
			<key>match</key>
			<string>\b(SV packet|Rcon from)\b</string>
			<key>name</key>
			<string>support.function.mohaa</string>
		</dict>
		<key>script_error</key>
		<dict>
			<key>match</key>
			<string>.+\^$</string>
			<key>name</key>
			<string>invalid</string>
		</dict>
		<key>string</key>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"+?</string>
			<key>name</key>
			<string>string</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.mohaa_log</string>
	<key>uuid</key>
	<string>253f50ef-27bb-4bfa-a191-534f3bbaa626</string>
</dict>
</plist>
